export const key = 'dictionaryFlashcard/User/page/ListMyCartset';

export const API_GET_ALL_MY_CARDSET = `${key}/API_GET_ALL_MY_CARDSET`;
export const API_GET_ALL_MY_CARDSET_SUCCESS = `${key}/API_GET_ALL_MY_CARDSET_SUCCESS`;
export const API_GET_ALL_MY_CARDSET_ERROR = `${key}/API_GET_ALL_MY_CARDSET_ERROR`;

export const API_UPDATE_NAME_CARDSET = `${key}/API_UPDATE_NAME_CARDSET`;
export const API_UPDATE_NAME_CARDSET_SUCCESS = `${key}/API_UPDATE_NAME_CARDSET_SUCCESS`;
export const API_UPDATE_NAME_CARDSET_ERROR = `${key}/API_UPDATE_NAME_CARDSET_ERROR`;
